name = "DackeLab"
uuid = "c4b269bd-7a1e-41dd-ad40-fdfc854795c7"
repo = "https://github.com/yakir12/DackeLab"
description = "This is the registry of the Dacke lab"

[packages]
ee64474f-0879-4582-97c7-e60ff50c5730 = { name = "Format2DB", path = "F/Format2DB" }
